// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "message.list", input: ListMessageArgs, result: Message[] } | 
        { key: "settings.theme", input: never, result: Theme },
    mutations: 
        { key: "message.send", input: string, result: null } | 
        { key: "settings.theme", input: Theme, result: null },
    subscriptions: never
};

/**
 * Arguments for the list messages query.
 */
export type ListMessageArgs = { after: number | null }

export type Message = { id: number; content: string; author: string; timestamp: string }

/**
 * The theme of the application.
 */
export type Theme = "Light" | "Dark"
