// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "settings.theme", input: never, result: Theme },
    mutations: 
        { key: "settings.theme", input: Theme, result: null },
    subscriptions: never
};

/**
 * The theme of the application.
 */
export type Theme = "Light" | "Dark"
