[workspace]
resolver = "2"
members = ["crates/*", "apps/desktop/src-tauri"]

[workspace.dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
thiserror = { version = "1" }
tokio = { version = "1", features = ["full"] }
