[package]
name = "lighthouse"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true  }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
