[package]
name = "string-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
flate2 = "1"
prost = "0.12"
prost-types = "0.12"
thiserror = { workspace = true }

[build-dependencies]
glob = "0.3"
prost-build = "0.12"
