[package]
name = "string-comm"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = { workspace = true }
tokio = { workspace = true }

byteorder = "1"
tracing = "0.1"

string-protocol = { path = "../protocol" }
