[package]
name = "comm"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = { workspace = true }
tokio = { workspace = true }

byteorder = "1"
tracing = "0.1"

protocol = { path = "../protocol" }

x25519-dalek = "^2.0.0"
double-ratchet-rs = "0.4.6"
rand = "0.8.5"
hex = "0.4.3"
